# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

schedules:
- cron: "37 22 * * 0"
  displayName: every Sunday, at 22:37
  branches:
    include:
      - main
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    sudo apt-get install python3-venv
    python3 -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  displayName: 'Set up the env'

- script: |
    source venv/bin/activate
    python run.py
  displayName: 'Build the list of CVEs with exploits'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/cves.txt'
    artifact: 'cves_txt'
    publishLocation: 'pipeline'
